# Generated by Django 5.2 on 2025-04-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='subspecialty',
            field=models.CharField(blank=True, choices=[('neuro', 'Neuro'), ('msk', 'MSK'), ('body', 'Body'), ('chest', 'Chest'), ('hn', 'Head & Neck'), ('nucmed', 'Nuclear Medicine'), ('peds', 'General Pediatrics'), ('ir', 'Interventional')], help_text='Radiology subspecialty area', max_length=10),
        ),
    ]
