# Generated by Django 5.2 on 2025-04-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_case_subspecialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='modality',
            field=models.CharField(blank=True, choices=[('xr', 'X-Ray'), ('ct', 'CT'), ('mri', 'MRI'), ('us', 'Ultrasound'), ('nm', 'Nuclear Medicine'), ('fluoro', 'Fluoroscopy'), ('angio', 'Angiography/Interventional')], help_text='Imaging modality used', max_length=10),
        ),
    ]
