# Generated by Django 5.2 on 2025-04-27 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_case_modality'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='dicom_path',
            field=models.CharField(blank=True, help_text='Path to DICOM storage directory', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='teaching_points',
            field=models.TextField(blank=True, help_text='Educational notes about this case', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Feedback'), ('feedback_ready', 'Feedback Ready')], default='draft', help_text='Current status of the report', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='submission_date',
            field=models.DateTimeField(blank=True, help_text='When the report was submitted for feedback', null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], help_text='Case difficulty level', max_length=50),
        ),
        migrations.CreateModel(
            name='DicomSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_instance_uid', models.CharField(max_length=255, unique=True)),
                ('series_number', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('modality', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='api.case')),
            ],
            options={
                'verbose_name_plural': 'DICOM Series',
                'ordering': ['series_number'],
            },
        ),
        migrations.CreateModel(
            name='DicomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop_instance_uid', models.CharField(max_length=255, unique=True)),
                ('instance_number', models.IntegerField(blank=True, null=True)),
                ('file_path', models.CharField(max_length=500)),
                ('thumbnail_path', models.CharField(blank=True, max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.dicomseries')),
            ],
            options={
                'ordering': ['instance_number'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The LLM-generated feedback content')),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('flagged', models.BooleanField(default=False, help_text='Flagged by user as problematic or unhelpful')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='api.report')),
            ],
        ),
    ]
